let languageData =[
  {
    "id": 1,
    "langname": "Arabic",
    "word": "مرحبا",
    "pronounciation": "marhabaan",
    "leftAlign": false,
    "speakers": 274,
  },
  {
    "id": 2,
    "langname": "Basque",
    "word": "Kaixo",
    "pronounciation": "kai-sho",
    "leftAlign": true,
    "speakers": 2,
  },
  {
    "id": 3,
    "langname": "Bengali",
    "word": "হ্যালো",
    "pronounciation": "Hyālō",
    "leftAlign": true,
    "speakers": 268,
  },
  {
    "id": 4,
    "langname": "Catalan",
    "word": "Hola",
    "pronounciation": null,
    "leftAlign": true,
    "speakers": 10,
  },
  {
    "id": 5,
    "langname": "Mandarin Chinese",
    "word": "你好",
    "pronounciation": "Nǐ hǎo",
    "leftAlign": true,
    "speakers": 1120,
  },
  {
    "id": 6,
    "langname": "Danish",
    "word": "Hej",
    "pronounciation": "/hej/",
    "leftAlign": true,
    "speakers": 10,
  },
  {
    "id": 7,
    "langname": "English",
    "word": "Hello",
    "pronounciation": "heh·low",
    "leftAlign": true,
    "speakers": 1348,
  },
  {
    "id": 8,
    "langname": "Filipino",
    "word": "Kamusta",
    "pronounciation": "kamustá",
    "leftAlign": true,
    "speakers": 45,
  },
  {
    "id": 9,
    "langname": "French",
    "word": "Bonjour",
    "pronounciation": "bown·zhoor",
    "leftAlign": true,
    "speakers": 267,
  },
  {
    "id": 10,
    "langname": "German",
    "word": "Hallo",
    "pronounciation": null,
    "leftAlign": true,
    "speakers": 135,
  },
  {
    "id": 11,
    "langname": "Hawaiian",
    "word": "aloha",
    "pronounciation": "ah-LO-hah",
    "leftAlign": true,
    "speakers": 1,
  },
  {
    "id": 12,
    "langname": "Hindi",
    "word": "नमस्ते",
    "pronounciation": "namaste",
    "leftAlign": true,
    "speakers": 600,
  },
  {
    "id": 13,
    "langname": "Indonesian",
    "word": "selamat",
    "pronounciation": "suh-lah-mat",
    "leftAlign": true,
    "speakers": 199,
  },
  {
    "id": 14,
    "langname": "Italian",
    "word": "Ciao",
    "pronounciation": "chaw",
    "leftAlign": true,
    "speakers": 68,
  },
  {
    "id": 15,
    "langname": "Japanese",
    "word": "こんにちは",
    "pronounciation": "Kon'nichiwa",
    "leftAlign": true,
    "speakers": 126,
  },
  {
    "id": 16,
    "langname": "Korean",
    "word": "안녕하세요",
    "pronounciation": "annyeonghaseyo",
    "leftAlign": true,
    "speakers": 82,
  },
  {
    "id": 17,
    "langname": "Marathi",
    "word": "नमस्कार",
    "pronounciation": "Namaskāra",
    "leftAlign": true,
    "speakers": 99,
  },
  {
    "id": 18,
    "langname": "Oromo",
    "word": "akkam",
    "pronounciation": null,
    "leftAlign": true,
    "speakers": 38,
  },
  {
    "id": 19,
    "langname": "Persian",
    "word": "سلام",
    "pronounciation": "Salām",
    "leftAlign": false,
    "speakers": 110,
  },
  {
    "id": 20,
    "langname": "Portuguese",
    "word": "Olá",
    "pronounciation": null,
    "leftAlign": true,
    "speakers": 258,
  },
  {
    "id": 21,
    "langname": "Romanian",
    "word": "Buna ziua",
    "pronounciation": null,
    "leftAlign": true,
    "speakers": 30,
  },
  {
    "id": 22,
    "langname": "Russian",
    "word": "Привет",
    "pronounciation": "Privet",
    "leftAlign": true,
    "speakers": 258,
  },
  {
    "id": 23,
    "langname": "Spanish",
    "word": "Hola",
    "pronounciation": null,
    "leftAlign": true,
    "speakers": 543,
  },
  {
    "id": 24,
    "langname": "Swahili",
    "word": "hujambo",
    "pronounciation": null,
    "leftAlign": true,
    "speakers": 69,
  },
  {
    "id": 25,
    "langname": "Thai",
    "word": "สวัสดี",
    "pronounciation": "S̄wạs̄dī",
    "leftAlign": true,
    "speakers": 61,
  },
  {
    "id": 26,
    "langname": "Turkish",
    "word": "Merhaba",
    "pronounciation": null,
    "leftAlign": true,
    "speakers": 88,
  },
  {
    "id": 27,
    "langname": "Ukranian",
    "word": "Здравствуйте",
    "pronounciation": "Zdravstvuyte",
    "leftAlign": true,
    "speakers": 35,
  },
  {
    "id": 28,
    "langname": "Urdu",
    "word": "ہیلو",
    "pronounciation": null,
    "leftAlign": false,
    "speakers": 230,
  },
  {
    "id": 29,
    "langname": "Vietnamese",
    "word": "xin chào",
    "pronounciation": null,
    "leftAlign": true,
    "speakers": 77,
  },
  {
    "id": 30,
    "langname": "Zulu",
    "word": "Sawubona",
    "pronounciation": null,
    "leftAlign": true,
    "speakers": 12,
  }
 ];

 export default languageData;

